### ISSUE TITLE
Support laravel 6.0

### ISSUE THREAD

**Issue by jordiepasman** [hoyvoy/laravel-cross-database-subqueries#15]
I saw that you merged a pull request for Laravel 6.0 support, but you haven`t released it yet.

Could you release the support for Laravel 6.0?

Thanks!

**Comment by repat** [comment]
@samuelhoyvoy I saw that you created a version on GitHub yesterday but it seems like your GitHub Webhook is broken, please check: https://packagist.org/packages/hoyvoy/laravel-cross-database-subqueries still only shows v5.6

**Comment by samuelhoyvoy** [comment]
Done!
